# Generated by Django 3.2.8 on 2022-02-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineAppointmentApp', '0002_auto_20220129_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='contacts',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
