# Generated by Django 3.2.8 on 2022-02-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineAppointmentApp', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='gender',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
